using System.Linq.Expressions;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Loader;
using HarmonyLib;
using NeoModLoader.constants;
using NeoModLoader.utils;

namespace NeoModLoader.AndroidCompatibilityModule.TranspilerSupport;

/// <summary>
/// tells NML to not replace the IL2CPP function you are transpiling with a managed one
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class)]
public class IgnoreTranspilerSupport : Attribute
{
}
/// <summary>
/// Stores the Managed Replacement of an IL2CPP method and its transpilers
/// </summary>
public class MirrorData
{
    internal MirrorData(DynamicMethod method, List<MethodInfo> transpilers)
    {
        Method = method.CreateDelegate(Expression.GetDelegateType(
            method.GetParameters().Select(p => p.ParameterType)
                .Append(method.ReturnType)
                .ToArray()
        ));
        Transpilers = new SortedList<MethodInfo>(HarmonyUtils.SortByPriority, transpilers);
    }
    private MirrorData() { }
    /// <summary>
    /// the IL2CPP method replacer generated by NML. calls the Managed <see cref="Method"/> which is modified by <see cref="Transpilers"/>
    /// </summary>
    public MethodInfo Replacer { get; internal set; }
    public readonly Delegate Method;
    internal readonly SortedList<MethodInfo> Transpilers;
    /// <summary>
    /// all prefixes applied to the mirror, you can add and remove them as you please
    /// </summary>
    public readonly SortedList<MethodInfo> Prefixes = new(HarmonyUtils.SortByPriority);
    /// <summary>
    /// gets all transpilers applied to this Mirror
    /// </summary>
    public List<MethodInfo> GetTranspilers()
    {
        return Transpilers.GetList();
    }
}
/// <summary>
/// A utility which replaces IL2CPP methods with managed methods (from the PC version) for transpilers
/// </summary>
public static class TranspilerSupport
{
     private static Dictionary<MethodBase, MirrorData> Mirrors = new();
     /// <summary>
     /// gets the mirror of a method from assembly-csharp, null if not found
     /// </summary>
     public static MirrorData GetMirror(MethodBase Method)
     {
         return Mirrors.GetValueOrDefault(Method);
     }
     /// <summary>
     /// Invokes a Mirror by its IL2CPP function. throws an exception if doesnt exist
     /// </summary>
    public static object InvokeMirror(MethodBase original, object[] args)
    {
        MirrorData Data = GetMirror(original);
        if (Data == null)
        {
            throw new ArgumentException("The Method doesnt have a Mirror Method!");
        }
        foreach (var Prefix in Data.Prefixes)
        {
            var result = HarmonyUtils.InvokePrefix(Prefix, ref args, out bool replaced);
            if (replaced)
            {
                return result;
            }
        }
        return Data.Method.DynamicInvoke(args);
    }
    private static Harmony _harmony;
    /// <summary>
    /// the assembly from the PC version
    /// </summary>
    public static Assembly ManagedAssembly { get; private set; }
    /// <summary>
    /// the IL2CPP Assembly
    /// </summary>
    public static Assembly NativeAssembly { get; private set; }
    internal static void Initialize(Harmony harmony)
    {
        MirroredAssemblies.Init();
        ManagedAssembly = MirroredAssemblies.LoadMirrorAssembly(Paths.PublicizedAssemblyPath);
        NativeAssembly = typeof(Actor).Assembly;
        _harmony = harmony;

        var patchMethod = typeof(Harmony).GetMethod("Patch", 
            BindingFlags.Public | BindingFlags.Instance,
            [typeof(MethodBase),typeof(MethodInfo),typeof(MethodInfo),typeof(MethodInfo),typeof(MethodInfo),typeof(MethodInfo)
            ]);
        harmony.Patch(patchMethod, new HarmonyMethod(
            typeof(TranspilerSupport), 
            nameof(PatchPrefix)
        ));
        var GetField = AccessTools.Method(typeof(AccessTools), nameof(AccessTools.Field),
            new[] { typeof(Type), typeof(string) });
        harmony.Patch(GetField, new HarmonyMethod(ManagedField));
    }
    static void ManagedField(ref Type type)
    {
        if (Path.GetFileName(type.Assembly.Location) == "Assembly-CSharp.dll")
        {
            type = RemapType(type, ManagedAssembly);
        }
    }
    static void CheckPrefix(MethodBase original, ref MethodInfo Prefix)
    {
        if (!Mirrors.TryGetValue(original, out var mirror)) return;
        mirror.Prefixes.Add(Prefix);
        Prefix = null;
    }
    private static void PatchPrefix(MethodBase original, ref MethodInfo transpiler, ref MethodInfo prefix)
    {
        if (!ShouldRedirect(original))
        {
            return;
        }
        CheckPrefix(original, ref prefix);
        if (transpiler == null || transpiler.DeclaringType == null) return;
        if (transpiler.GetCustomAttribute<IgnoreTranspilerSupport>() != null ||
            transpiler.DeclaringType.GetCustomAttribute<IgnoreTranspilerSupport>() != null)
        {
            return;
        }
        if (!Mirrors.TryGetValue(original, out MirrorData value))
        {
            var copy = BuildRedirectPrefix(original);
            MirrorData data = BuildMirrorMethod(original, [transpiler]);
            data.Replacer = copy;
            Mirrors.Add(original, data);
            _harmony.Patch(original, copy);
            Patches patches = Harmony.GetPatchInfo(original);
            if (patches != null)
            {
                foreach (Patch Prefix in patches.Prefixes)
                {
                    _harmony.Unpatch(original, Prefix.PatchMethod);
                    data.Prefixes.Add(Prefix.PatchMethod);
                }
            }
        }
        else
        {
            var transpilers = value.Transpilers;
            if (transpiler != null)
            {
                transpilers ??= new SortedList<MethodInfo>(HarmonyUtils.SortByPriority);
                transpilers.Add(transpiler);
            }
            Mirrors[original] = BuildMirrorMethod(original, transpilers.GetList());
        }
        transpiler = null;
    }
    /// <summary>
    /// Transforms a Field into a getter / setter method
    /// </summary>
    public static bool TransformField(ref OpCode Opcode, ref object operand)
    {
        if (operand is not FieldInfo Field) return false;
        string Name = Field.Name;
        Type NewType = RemapType(Field.DeclaringType, ManagedAssembly);
        Type FieldType = RemapType(Field.FieldType, ManagedAssembly);
        MethodInfo Method = null;
        if (Opcode == OpCodes.Ldfld || Opcode == OpCodes.Ldsfld)
        {
            Method = AccessTools.Method(NewType, "get_"+Name);
        }
        else if (Opcode == OpCodes.Stfld || Opcode == OpCodes.Stsfld)
        {
            Method = AccessTools.Method(NewType, "set_"+Name, [FieldType]);
        }
        if (Method == null)
        {
            return false;
        }
        operand = Method;
        if (Opcode == OpCodes.Ldsfld || Opcode == OpCodes.Stsfld)
        {
            Opcode = OpCodes.Call;
        }
        else
        {
            Opcode = OpCodes.Callvirt;
        }
        return true;
    }
    private static bool ShouldRedirect(MethodBase method)
    {
        if (method.IsGenericMethod || method.DeclaringType.IsGenericType)
            return false;
        return Path.GetFileName(method.DeclaringType.Assembly.Location) == "Assembly-CSharp.dll";
    }
    private static MirrorData BuildMirrorMethod(MethodBase original, List<MethodInfo> transpilers = null)
{
    var mirrorType = ManagedAssembly.GetType(original.DeclaringType.FullName);
    var paramms = original.GetParameters().Select(p => p.ParameterType).ToArray();
    var paramTypes = paramms.Select(t => RemapType(t, ManagedAssembly)).ToArray();

    MethodInfo mirrorMethod = mirrorType.GetMethod(
        original.Name,
        BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static,
        null,
        paramTypes,
        null
    );

    DynamicMethod dynMethod = new DynamicMethod(
        original.Name + "_managed",
        RemapType(mirrorMethod.ReturnType, NativeAssembly),
        paramms,
        original.DeclaringType,
        skipVisibility: true
    );

    var generator = dynMethod.GetILGenerator();

    // Get instructions and apply transpilers before emitting
    List<CodeInstruction> instructions = PatchProcessor.GetOriginalInstructions(mirrorMethod);
    foreach (var t in instructions)
    {
        t.operand = RemapOperand(t.operand);
    }
    if (transpilers != null)
    {
        foreach (var transpiler in transpilers)
        {
            var transpilerParams = transpiler.GetParameters();
            var args = transpilerParams.Select(p =>
            {
                if (p.ParameterType == typeof(IEnumerable<CodeInstruction>))
                    return (object)instructions;
                if (p.ParameterType == typeof(ILGenerator))
                    return (object)generator;
                if (p.ParameterType == typeof(MethodBase))
                    return (object)original;
                return null;
            }).ToArray();
            instructions = ((IEnumerable<CodeInstruction>)transpiler.Invoke(null, args)).ToList();
        }
    }
    var locals = mirrorMethod.GetMethodBody()?.LocalVariables ?? [];
    var localMap = new Dictionary<int, LocalBuilder>();
    foreach (var local in locals)
    {
        var newLocal = generator.DeclareLocal(RemapType(local.LocalType, NativeAssembly));
        localMap[local.LocalIndex] = newLocal;
    }
    var labelMap = new Dictionary<Label, Label>();
    Label GetOrCreateLabel(Label old)
    {
        if (!labelMap.TryGetValue(old, out var newLabel))
        {
            newLabel = generator.DefineLabel();
            labelMap[old] = newLabel;
        }
        return newLabel;
    }
    foreach (var instr in instructions)
    {
        foreach (var label in instr.labels)
            generator.MarkLabel(GetOrCreateLabel(label));
        var operand = instr.operand;
        operand = operand switch
        {
            LocalBuilder lb when localMap.TryGetValue(lb.LocalIndex, out var mappedLocal) => mappedLocal,
            Label lbl => GetOrCreateLabel(lbl),
            Label[] lbls => lbls.Select(GetOrCreateLabel).ToArray(),
            _ => operand
        };
        TransformField(ref instr.opcode, ref operand);
        generator.EmitInstruction(instr.opcode, operand);
    }
    return new MirrorData(dynMethod, transpilers);
}
    private static MethodInfo BuildRedirectPrefix(MethodBase original)
{
    var parameters = original.GetParameters();
    var paramTypes = parameters.Select(p => p.ParameterType).ToList();
    var returnType = original is MethodInfo mi ? mi.ReturnType : typeof(void);

    if (!original.IsStatic)
        paramTypes.Insert(0, original.DeclaringType);

    if (returnType != typeof(void))
        paramTypes.Add(returnType.MakeByRefType());

    var prefix = new DynamicMethod(
        original.Name + "_redirect",
        typeof(bool),
        paramTypes.ToArray(),
        typeof(Redirects),
        true
    );

    var il = prefix.GetILGenerator();
    
    il.Emit(OpCodes.Ldtoken, original as MethodInfo ?? throw new Exception());
    il.Emit(OpCodes.Call, typeof(MethodBase)
        .GetMethod(nameof(MethodBase.GetMethodFromHandle), new[] { typeof(RuntimeMethodHandle) }));

    il.Emit(OpCodes.Call, AccessTools.Method(typeof(TranspilerSupport), nameof(GetMirror)));

    var mirrorLocal = il.DeclareLocal(typeof(MirrorData));
    il.Emit(OpCodes.Stloc, mirrorLocal);
    
    il.Emit(OpCodes.Ldloc, mirrorLocal);
    il.Emit(OpCodes.Ldfld, typeof(MirrorData).GetField(nameof(MirrorData.Method)));

    var delegateType = typeof(Delegate);
    var invoke = delegateType.GetMethod("DynamicInvoke", new[] { typeof(object[]) });
    
    int argCount = original.IsStatic ? parameters.Length : parameters.Length + 1;

    il.Emit(OpCodes.Ldc_I4, argCount);
    il.Emit(OpCodes.Newarr, typeof(object));

    for (int i = 0; i < argCount; i++)
    {
        il.Emit(OpCodes.Dup);
        il.Emit(OpCodes.Ldc_I4, i);
        il.Emit(OpCodes.Ldarg, i);

        if (paramTypes[i].IsValueType)
            il.Emit(OpCodes.Box, paramTypes[i]);

        il.Emit(OpCodes.Stelem_Ref);
    }

    il.Emit(OpCodes.Callvirt, invoke);

    if (returnType != typeof(void))
    {
        var resultLocal = il.DeclareLocal(returnType);

        if (returnType.IsValueType)
            il.Emit(OpCodes.Unbox_Any, returnType);
        else
            il.Emit(OpCodes.Castclass, returnType);

        il.Emit(OpCodes.Stloc, resultLocal);

        il.Emit(OpCodes.Ldarg, paramTypes.Count - 1);
        il.Emit(OpCodes.Ldloc, resultLocal);

        if (returnType.IsValueType)
            il.Emit(OpCodes.Stobj, returnType);
        else
            il.Emit(OpCodes.Stind_Ref);
    }
    else
    {
        il.Emit(OpCodes.Pop);
    }

    il.Emit(OpCodes.Ldc_I4_0);
    il.Emit(OpCodes.Ret);

    return prefix;
}
    private static object RemapOperand(object operand)
    {
        switch (operand)
        {
            case MethodInfo m when m.DeclaringType?.Assembly == ManagedAssembly:
                return AccessTools.Method(
                    RemapType(m.DeclaringType, NativeAssembly),
                    m.Name,
                    m.GetParameters()
                        .Select(p => RemapType(p.ParameterType, NativeAssembly))
                        .ToArray()
                );

            case ConstructorInfo c when c.DeclaringType?.Assembly == ManagedAssembly:
                return AccessTools.Constructor(
                    RemapType(c.DeclaringType, NativeAssembly),
                    c.GetParameters()
                        .Select(p => RemapType(p.ParameterType, NativeAssembly))
                        .ToArray()
                );

            case Type t when t.Assembly == ManagedAssembly:
                return RemapType(t, NativeAssembly);

            case FieldInfo f when f.DeclaringType?.Assembly == ManagedAssembly:
                return AccessTools.Field(
                    RemapType(f.DeclaringType, NativeAssembly),
                    f.Name
                );

            default:
                return operand;
        }
    }

    private static Type RemapType(Type type, Assembly targetAssembly)
    {
        if (type == null)
            return null;

        if (type.Assembly == targetAssembly)
            return type;

        if (type.IsByRef)
        {
            var element = RemapType(type.GetElementType(), targetAssembly);
            return element.MakeByRefType();
        }

        if (type.IsPointer)
        {
            var element = RemapType(type.GetElementType(), targetAssembly);
            return element.MakePointerType();
        }

        if (type.IsArray)
        {
            var element = RemapType(type.GetElementType(), targetAssembly);
            return type.GetArrayRank() == 1
                ? element.MakeArrayType()
                : element.MakeArrayType(type.GetArrayRank());
        }

        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            var remappedDef = RemapType(genericDef, targetAssembly);

            var args = type.GetGenericArguments()
                .Select(t => RemapType(t, targetAssembly))
                .ToArray();

            return remappedDef.MakeGenericType(args);
        }

        var remapped = targetAssembly.GetType(type.FullName);

        return remapped ?? type;
    }
}

public class MirroredAssemblies : AssemblyLoadContext
{
    public MirroredAssemblies() : base("MirrorContext", isCollectible: true) { }

    protected override Assembly Load(AssemblyName assemblyName) => null;
    private static MirroredAssemblies Instance;
    internal static void Init(){
        Instance = new  MirroredAssemblies();
    }
    public static Assembly LoadMirrorAssembly(string path)
    {
        return Instance.LoadFromAssemblyPath(Path.GetFullPath(path));
    }
    public static void Destroy()
    {
        Instance.Unload();
        Instance = null;
    }

    public static Type GetMirroredType(Type Type)
    {
        foreach (var assembly in Instance.Assemblies)
        {
            Type type = assembly.GetType(Type.FullName);
            if(type != null)
            {
                return type;
            }
        }

        return null;
    }
}
/// <summary>
/// where Redirects are stored once built
/// </summary>
public static class Redirects
{
}
